:toc:
:toclevel: 5

== SSL DND (Donot Decrypt)
Proxy supports DND mode where it does not decrypt the SSL Traffic, rather just pipes the traffic to SSL Server.

Mechanically, this is exactly what happens when a security appliance like Netskope or Zscaler performs an "SSL Bypass" or "DoNotDecrypt" action.

=== Modes

==== 1. SSL Decrypt (Inspection)
The proxy terminates the TLS, decrypts the traffic to inspect for malware, and then re-encrypts it using its own certificate to send to the client.

==== 2. SSL DoNotDecrypt (Bypass/Tunnel) // Present Method
The proxy sees the CONNECT or the SNI (Server Name Indication) in the Client Hello, identifies it as "Trusted" 
(e.g., Financial or Health sites), and stops acting as a Layer 7 gateway. It drops down to Layer 4 (TCP) and just moves segments back and 
forth without looking at the payload, ie like a blind pipe.

=== Sequence Diagram

image:://www.plantuml.com/plantuml/png/XLHXRzem4FsUNt5gfGaa6YKX7IKQKrdQhTKcnWJLD8alNh12j62diJF6r1_V8pQo8wCY14GlxzwTxzxvLaXIosPRUXN-5rbH4IRX8YqBokIAXT783_0J9kCW22w02CZQLrtwlER_zh2WzLzQjoJHFdP9ZqpIcf7ooq_K3Vpe-bf_upOattNfEUTvIVsCRv4UHyWR-k4uyiCuYUDX6w8edZUPz6HM-KBMb6o1FiFxFhoyG1U4KHzQj5dRQ70I3VkJYUUHKiBbfq8yDnIMwHo6i2Dxs12s5XloXmxWORcS3s3vRG4hjcBWLE4nBYbmRCMnRTs6zchKujk-HzaQ3bmhGBVG1Dm4Du4XOcs7cZob2rSVTG0aiFWrEy8VhZhm0ARfrnCXBOpIwiXuAbStWVJxR7QVBi4CvZ08JsiWKOKeCHUDWW1IpXZSe-L-buNOqBN9YJqyLLUge0TQbXnwWXKJaxtl9j4ML7mKjn9Sfdl2u6wsKDrzkfixCxS5yrtIadyqjDu3pdPgdTlBTwPAcrTJKHt8NRzQHKp_DpLrV6GSfEfl-qGpAK1oUAfqYUyWfnBMH1B5TUnzmZmZh0DB2FquICPXzARXz3QvksR8HzUPHkaePJg5ekbiT63RmV0HxKxVfPmRlabc9DMpcKxN4lgrMGitIADLLHOPaGL7ps37RI-PEw6zzhI-mBT2JKToxSVpjyBRItxk-Z14TnNS8vY6sOlgefyVPwwScTSj_ZRRyXK0[SSL DND Diagram]

```plantuml
@startuml
participant "Client\n127.0.0.1:9000" as client
participant "Proxy Server" as server
participant "InternalGW\n10.255.255.254" as gw
participant "google.com\n142.253.192.14:443" as google

==(tcp.stream eq 6) || (tcp.stream eq 7)  || (udp.stream eq 0)  || (udp.stream eq 1)==

alt #Bisque TCP 3 way handshake, HTTP, TLS \n\n (tcp.stream eq 6)
note over client
127.0.0.1:9000(random)
end note
note over server
127.0.0.1:8080
end note
alt TCP
client -> server : SYN
client <- server : SYN, ACK
client -> server : ACK
end

alt HTTP
client -> server: CONNECT google.com:443
server -> client: ACK
server -> client: 200 Conn Established
end

alt TLS
client -> server : Client Hello (sni=google.com)
server -> client: Server Hello
end
end

alt #Cyan DNS over UDP (udp.stream eq 1)
server -> gw: DNS Query \n A google.com
gw -> server: DNS Query resp \n 142.253.192.14
end

alt #Azure 3 way handshake, TLS \n\n Server Connects to Upstream & get data \n\n (tcp.stream eq 7)
note over server
172.22.11.40:9120(random)
end note
note over google
142.253.192.14:443
end note

alt TCP
server -> google: SYN
server <- google: SYN,ACK
server -> google: ACK
end

alt TLS
server -> google: Client Hello (sni=google.com)
server <- google: ACK
google -> server: Server Hello
google <- server: ACK
google -> server: Application Data
end
end

alt #Bisque ProxyServer sends data to client \n\n (tcp.stream eq 6)
note over server
127.0.0.1:8080
end note
note over client
127.0.0.1:9000
end note

server -> client: Application Data
server <- client: ACK
server <- client: FIN
server -> client: ACK
end

@enduml
```